# Generated by Django 5.2.1 on 2025-07-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('IdUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('Usuario', models.TextField(max_length=20)),
                ('Email', models.TextField(max_length=128)),
                ('Contraseña', models.TextField(max_length=16)),
                ('Tipo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('IdProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=50)),
                ('Tipo', models.TextField(max_length=10)),
                ('Descripcion', models.TextField(max_length=64)),
                ('Imagen', models.ImageField(null=True, upload_to='Productos')),
            ],
        ),
    ]
