# Generated by Django 5.2.1 on 2025-07-11 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Usuarios',
        ),
    ]
