# Generated by Django 5.2.1 on 2025-07-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_login_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='IdProducto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='IdUsuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
